# eligibility: 1: directed	- 2: hyper	- 3: loops	- 4: multiple - 5: bipartite

ergm_configurations <- list(
  "gwesp" = list(name="gwesp", 
                 template="gwesp(decay={NUMBER}, fixed={BOOL})", 
                 default_vals=list(decay=0.1, fixed=TRUE), eligibility=rep(NA, 5)), 
  "edges" = list(name="edges", 
                 template="edges", 
                 default_vals=NA, 
                 eligibility=rep(NA, 5)),
  "kstar" = list(name="kstar", 
                 template="kstar(k={NUMBER}, attr={VERTEX})", 
                 default_vals=list(k=2, attr=NULL), eligibility=c(0,NA,NA,NA,NA)),
  "density" = list(name="density", 
                   template="density", 
                   default_vals=NA, eligibililty=rep(NA,5)),
  "mutual" = list(name="mutual", 
                  template="mutual({VERTEX}, diff={BOOL})", 
                  default_vals=list(attrname=NULL, diff=FALSE), eligibility=c(1,NA,NA,NA,NA)),
  "nodematch" = list(name="nodematch",
                     template="nodematch(attr={VERTEX}, diff={BOOL}, levels=NULL)",
                     default_vals=list(attr=NULL, diff=FALSE), eligibility=rep(NA,5)),
  "nodecov" = list(name="nodecov", 
                 template="nodecov(attr={VERTEX})", 
                 default_vals=list(attr=NULL), eligibility=rep(NA, 5)),
  "nodefactor" = list(name="nodefactor",
                      template="nodefactor(attr={VERTEX}, base={NUMBER}, levels=-1)",
                      default_vals=list(attr=NULL, base=1), eligibility=rep(NA, 5)),
  "absdiff (binary)"=list(name="absdiff", 
                          template="absdiff(attr={VERTEX}, pow={NUMBER})", 
                          default_vals=list(attr=NULL, pow=1), eligibility=c(NA,NA,NA,NA,NA)),
  "diff"=list(name=diff, 
              template="diff(attr={VERTEX},pow={NUMBER}, dir='{STRING}', sign.action='{STRING}')", 
              default_vals=list(attr=NULL, pow=1, dir='t-h', sign.action='identity'), eligibility=rep(NA,5)),
  "gwdegree"=list(name="gwdegree", 
                  template="gwdegree(decay={NUMBER}, fixed={BOOL}, attr={VERTEX}, cutoff={NUMBER}, levels=NULL)", 
                  default_vals=list(decay=.2, fixed=F, attr=NULL, cutoff=30), 
                  eligibility=c(0, NA, NA, NA, NA)),
  "nearsimmelian"=list(name="nearsimmelian", 
                       template="nearsimmelian", 
                       default_vals=NA, eligibility=c(1,NA,NA,NA,NA))
)
